spring:
  application:
    name: awesome-spring-ai-rag
  jmx:
    enabled: false
  ai:
    vectorstore:
      milvus:
        client:
          host: localhost
          port: 19530
          username: root
          password: milvus
        database-name: ${MILVUS_DATABASE:default}
        collection-name: ${MILVUS_COLLECTION:vector_store}
        initialize-schema: ${MILVUS_INIT_SCHEMA:true}
        embedding-dimension: ${MILVUS_EMBED_DIM:768}
        index-type: ${MILVUS_INDEX_TYPE:FLAT}
        metric-type: ${MILVUS_METRIC_TYPE:COSINE}

    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        options:
          model: ${OLLAMA_CHAT_MODEL:gemma:2b-instruct}
          temperature: ${OLLAMA_TEMPERATURE:0.0}
      embedding:
        options:
          model: ${OLLAMA_EMBED_MODEL:nomic-embed-text}
      init:
        pull-model-strategy: ${OLLAMA_INIT_PULL_MODEL_STRATEGY:always}
        timeout: ${OLLAMA_INIT_TIMEOUT:5m}
        max-retries: ${OLLAMA_INIT_MAX_RETRIES:3}
